# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: false

# Setup
title:               Zuriel Diaz
tagline:             'Full Stack Web Development'
description:         'Full Stack Web Development.'
# Local dev environment
url:                 http://127.0.0.1:4000
# Production environment
#url:                 https://zuriel-diaz.github.io
baseurl:             ''
paginate:            2

# About/contact
author:
  name:               Zuriel Diaz
  url:                https://zuriel-diaz.github.io
  email:              zurieldiazd@gmail.com
  twitter:            https://twitter.com/@ZurieLeader
  google_plus:        https://plus.google.com/105288612897908090179?rel=author
  github:             https://github.com/zuriel-diaz
  stackoverflow:      http://stackoverflow.com/users/6521429/zurieldiaz
  linkedin:           https://www.linkedin.com/in/zurieleader

# Custom vars
version:             1.0.0

# Gems 
gems:                [jekyll-paginate]
