# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               ZurielDiaz
tagline:             'Zuriel Diaz'
description:         'Welcome to my lab.'
url:                 https://zuriel-diaz.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Zuriel Diaz
  url:               https://twitter.com/ZurieLeader
  email:             zurieldiazd@gmail.com

# Custom vars
version:             1.0.0

# Gems 
gems: [jekyll-paginate]
